//
//  CreateDirectionRouter.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/11/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateDirectionRoutingLogic
{
  func routToFindLocation(segue: UIStoryboardSegue?)
}

protocol CreateDirectionDataPassing
{
  var dataStore: CreateDirectionDataStore? { get set}
}

class CreateDirectionRouter: NSObject, CreateDirectionRoutingLogic, CreateDirectionDataPassing
{
  weak var viewController: CreateDirectionViewController?
  var dataStore: CreateDirectionDataStore?
  
  // MARK: Routing
    func routToFindLocation(segue: UIStoryboardSegue?){
        if let segue = segue {
            if segue.identifier == "createTripSegue" {
                let destinationVC = segue.destination as! CreateTripViewController
                destinationVC.startingPoint = viewController?.startingPoint
                destinationVC.endPoint = viewController?.endPoint
                 destinationVC.response = viewController?.response
            }
            else {
                let destinationVC = segue.destination as! FindLocationViewController
                destinationVC.isStartPoint = (dataStore?.isStartPoint)!
                destinationVC.createDirectionVC = viewController!
            }
        }
    }

}
