//
//  LoginPresenter.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/7/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func handleOTPResponse(response: Bool, message: String)
    func handleVerifyOTPResponse(response: Bool, message: String)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
  
    func handleOTPResponse(response: Bool, message: String)
    {
        let viewModel = Login.ViewModel(success: response, message: message )
        viewController?.handleOTPResponse(viewModel: viewModel)
    }
    func handleVerifyOTPResponse(response: Bool, message: String)
    {
        let viewModel = Login.ViewModel(success: response, message: message )
        viewController?.handleVerifyOTPResponse(viewModel: viewModel)
    }
}
