//
//  LoginModels.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/7/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Foundation

enum Login
{
    // MARK: Use cases
    enum GetOTP
    {
        struct RequestOTP
        {
            let phone: String
            let name: String
        }
    }
    
    enum VerifyOTP
    {
        struct RequestVerification: Codable
        {
            let phone: String
            let otp: String
        }
    }
    
    struct ResponseOTP: Codable
    {
        let success: Bool
        let uid: String
    }
    struct ViewModel
    {
        let success: Bool
        let message: String
    }
}
