//
//  LoginWorker.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/7/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
    func getOTP(phone: String, name: String,completion: @escaping (Bool, String) -> Void)
    {
        MainWorker.taskForGETRequest(url: MainWorker.Endpoints.getOTP(phone, name).url, responseType: Login.ResponseOTP.self){ (response,error)
            in
            if let response = response {
                UserManager.shared.setUserData(phone: phone, name: name, id: response.uid)
                completion(response.success,response.uid)
            }
            else {
                completion(false,error?.localizedDescription ?? "")
            }
        }
    }
    
    func verifyOTP(body: Login.VerifyOTP.RequestVerification,completion: @escaping (Bool, String) -> Void)
    {
        var params = [String:String] ()
        params ["phone"] = body.phone
        params ["otp"] = body.otp
       MainWorker.taskForPOSTRequest(url: MainWorker.Endpoints.verifyOTP.url, responseType: Login.ResponseOTP.self, parameters: params){ (response,error)
            in
            if let response = response {
                
                completion(response.uid == "0" ? false : response.success,response.uid == "0" ? "Wrong OTP" : response.uid)
            }
            else {
                completion(false,error?.localizedDescription ?? "")
            }
        }
    }
}
