//
//  FindLocationRouter.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/12/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FindLocationRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol FindLocationDataPassing
{
  var dataStore: FindLocationDataStore? { get }
}

class FindLocationRouter: NSObject, FindLocationRoutingLogic, FindLocationDataPassing
{
  weak var viewController: FindLocationViewController?
  var dataStore: FindLocationDataStore?
}
