//
//  CreateTripInteractor.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/15/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateTripBusinessLogic
{
    func createTripOD(request: CreateTrip.Request)
}

protocol CreateTripDataStore
{
    //var name: String { get set }
}

class CreateTripInteractor: CreateTripBusinessLogic, CreateTripDataStore
{
    var presenter: CreateTripPresentationLogic?
    var worker: CreateTripWorker?
    
    // MARK: Do something
    func createTripOD(request: CreateTrip.Request)
    {
        worker = CreateTripWorker()
        worker?.createTripOD(body: request, completion: {
            ( success, data)
            in
            self.presenter?.presentResponse(sucess: success, data: data)
        })
        
    }
}
