//
//  CreateTripPresenter.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/15/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateTripPresentationLogic
{
    func presentResponse(sucess: Bool, data: String)
}

class CreateTripPresenter: CreateTripPresentationLogic
{
  weak var viewController: CreateTripDisplayLogic?
  
  // MARK: Do something
  
  func presentResponse(sucess: Bool, data: String)
  {
    viewController?.displaySomething(sucess: sucess, data: data)
  }
}
