//
//  MyDestinationListWorker.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/20/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MyDestinationListWorker
{
    func getMyTrips(completion: @escaping ([Trip], Error?) -> Void)
    {
        MainWorker.taskForGETRequest(url: MainWorker.Endpoints.getMyTrips.url, responseType: MyDestinationList.Response.self){ (response,error)
            in
            if let response = response {
                completion(response.data,nil)
            }
            else {
                completion([],error)
            }
        }
    }
    
    func deleteTicketrequest(body: MyDestinationList.RequestDeleteTicket,completion: @escaping (Bool, String) -> Void)
    {
        var params = [String:String] ()
        params ["uid"] = body.uid
        params ["trip_id"] = body.trip_id
        MainWorker.taskForPOSTRequest(url: MainWorker.Endpoints.deleteTicket.url, responseType: MyDestinationList.ResponseDeleteTicket.self, parameters: params){ (response,error)
            in
            if let response = response {
                completion( response.success, response.data)
            }
            else {
                completion(false,error?.localizedDescription ?? "")
            }
        }
    }
    
    func deleteTrip(body: MyDestinationList.RequestDeleteTrip,completion: @escaping (Bool, String) -> Void)
    {
        var params = [String:String] ()
        params ["trip_id"] = body.trip_id
        MainWorker.taskForPOSTRequest(url: MainWorker.Endpoints.deleteTrip.url, responseType: MyDestinationList.ResponseTicketBooking.self, parameters: params){ (response,error)
            in
            if let response = response {
                
                completion( response.success, String(response.uid))
            }
            else {
                completion(false,error?.localizedDescription ?? "")
            }
        }
    }
}
