//
//  MyDestinationListPresenter.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/20/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyDestinationListPresentationLogic
{
    func presentList(trip: [Trip], error: Error?)
    func deleteBookingRequest(success: Bool, message: String,posintion: Int)
    func deleteTrip(success: Bool, message: String,posintion: Int)
}

class MyDestinationListPresenter: MyDestinationListPresentationLogic
{
    weak var viewController: MyDestinationListDisplayLogic?
    
    // MARK: Do something
    func presentList(trip: [Trip], error: Error?)
    {
        viewController?.displayMyTrips(trip: trip, error: error)
    }
    func deleteTrip(success: Bool, message: String, posintion: Int) {
        viewController?.deleteTrip(success: success, message: message, posintion: posintion)
    }
    func deleteBookingRequest(success: Bool, message: String,posintion: Int)
    {
        viewController?.deleteBookingRequest(success: success, message: message, posintion: posintion)
    }
}
