//
//  TripBookingRequestsModels.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/20/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TripBookingRequests
{
  // MARK: Use cases
    struct Request: Codable
    {
        let uid: String
        let trip_id: String
        let creater_id: String
        let status: String
        let position: Int
    }
    struct Response : Codable
    {
        let success: Bool
        let data: [TripRequest]
    }
    struct ViewModel
    {
    }
  
}
