//
//  TripBookingRequestsRouter.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/20/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TripBookingRequestsRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol TripBookingRequestsDataPassing
{
  var dataStore: TripBookingRequestsDataStore? { get }
}

class TripBookingRequestsRouter: NSObject, TripBookingRequestsRoutingLogic, TripBookingRequestsDataPassing
{
  weak var viewController: TripBookingRequestsViewController?
  var dataStore: TripBookingRequestsDataStore?
}
