//
//  TripBookingRequestsViewController.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/20/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TripBookingRequestsDisplayLogic: class
{
    func updateBookingStatus(success: Bool, message: String,posintion: Int)
    func displayMyTrips(tripRequest: [TripRequest], error: Error?)
}

class TripBookingRequestsViewController: UIViewController, TripBookingRequestsDisplayLogic
{
    
    //MARK: outlets
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var noItemView: UIView!
    @IBOutlet weak var navigationIten: UINavigationItem!
    
    // MARK: Variables
    var spinner: UIActivityIndicatorView?
    let formatter: DateFormatter = DateFormatter()
    let formatterLong: DateFormatter = DateFormatter()
    var interactor: TripBookingRequestsBusinessLogic?
    var router: (NSObjectProtocol & TripBookingRequestsRoutingLogic & TripBookingRequestsDataPassing)?
    
    // MARK: Lifecycle methods
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    override func viewDidLoad()
    {
        super.viewDidLoad()
        spinner = SpinnerView.showLoader(view: view)
        let tapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(imageTapped(tapGestureRecognizer:)))
        noItemView.isUserInteractionEnabled = true
        noItemView.addGestureRecognizer(tapGestureRecognizer)
        self.navigationIten.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(showfindRouteController))
        self.navigationIten.rightBarButtonItem?.tintColor = UIColor.white
        self.navigationIten.leftBarButtonItem = UIBarButtonItem(title: "Logout", style: .plain, target: self, action: #selector(logOut))
        self.navigationIten.rightBarButtonItem?.tintColor = UIColor.white
        self.navigationIten.leftBarButtonItem?.tintColor = UIColor.white
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        spinner?.startAnimating()
        noItemView.isHidden = true
        interactor?.getMyTripRequests()
    }
    
    // MARK: Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    
    // MARK: Setup
    private func setup()
    {
        formatter.dateFormat = "HH:mm a, dd MMM"
        formatterLong.dateFormat = "dd MMM'' yyyy"
        let viewController = self
        let interactor = TripBookingRequestsInteractor()
        let presenter = TripBookingRequestsPresenter()
        let router = TripBookingRequestsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    //MARK: Navigation callback
    @objc func showfindRouteController(_ updateLocation: Bool){
        self.performSegue(withIdentifier: "findRouteSegue", sender: nil)
    }
    @objc func logOut(){
        AlertController.showAlert("Logout", message: "Sure to logout?",actionLabel: "Logout",completion: {
            (alert)
            in
            UserManager.shared.resetUserData()
            self.dismiss(animated: true, completion: nil)
        })
        
    }
    //MARK: IBActions
    @objc func imageTapped(tapGestureRecognizer: UITapGestureRecognizer)
    {
        noItemView.isHidden = true
        spinner?.startAnimating()
        interactor?.getMyTripRequests()
    }
    
    // MARK: Delegate method -> TripBookingRequestsDisplayLogic
    func displayMyTrips(tripRequest: [TripRequest], error: Error?)
    {
        spinner?.stopAnimating()
        TripModel.myTripRequestList = tripRequest
        tableView.reloadData()
        if  TripModel.myTripRequestList.count == 0
        {     noItemView.isHidden = false
        }
    }
    func updateBookingStatus(success: Bool, message: String,posintion: Int) {
        spinner?.stopAnimating()
        if success {
            if 3 == Int(message){
                TripModel.myTripRequestList.remove(at: posintion)
            }
            else{
                TripModel.myTripRequestList[posintion].status = Int(message)!
            }
            tableView.reloadData()
            if  TripModel.myTripRequestList.count == 0
            {     noItemView.isHidden = false
            }
        }
        else {
            AlertController.showAlert("Error", message: message)
        }
    }
}

//MARK: TableView Delegates
extension TripBookingRequestsViewController : UITableViewDataSource, UITableViewDelegate{
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return TripModel.myTripRequestList.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "TripTableViewCell") as! RequestBookingTableCell
        
        let trip = TripModel.myTripRequestList[indexPath.row]
        cell.name.text = "\(trip.name) request for a seat"
        cell.title.text = trip.title
        cell.subTitle?.text = "\(formatter.string(from: Date(milliseconds: Int(trip.startsdate)))) to \(formatterLong.string(from: Date(milliseconds: Int(trip.enddate))))"
        cell.initialLabel?.text = trip.name.components(separatedBy: " ").reduce("") { ($0 == "" ? "" : "\($0.first!)") + "\($1.first!)"}.uppercased()
        if 0 ==  trip.status {
            cell.ticketButton.setImage(UIImage(named: "requested.png"), for: .normal)
        }
        else if trip.status == 1 {
            cell.ticketButton.setImage(UIImage(named: "accepted.png"), for: .normal)
        }
        else if trip.status == 2 {
            cell.ticketButton.setImage(UIImage(named: "info.png"), for: .normal)
        }
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        showAlert(position: indexPath.row)
        
    }
    func showAlert(position: Int){
        
        let trip = TripModel.myTripRequestList[position]
        var  title: String =  "\(trip.name) request for a seat"
        var message: String = "You can accept or decline the booking request"
        if trip.status == 1 {
            title = "You have accepted \(trip.name)''s request"
            message = "You can decline the booking request"
        }
        if trip.status == 0 {
            AlertController.showAlert(title, message: message,actionLabel: "Accept", actionLabel2: "Decline",completion: {(UIAlertAction)
                in
                self.spinner?.startAnimating()
                let request = TripBookingRequests.Request(uid: "\(trip.uid)", trip_id: "\(trip.trip_id)", creater_id: UserManager.shared.getUserId()!, status: ("1") , position: position)
                self.interactor?.updateTicket(request: request)
            }
                ,completion2: {(UIAlertAction)
                    in
                    self.spinner?.startAnimating()
                    let request = TripBookingRequests.Request(uid: "\(trip.uid)", trip_id: "\(trip.trip_id)", creater_id: UserManager.shared.getUserId()!, status: ("3") , position: position)
                    self.interactor?.updateTicket(request: request)
            })
        }
        else if trip.status == 1 {
            AlertController.showAlert(title, message: message,actionLabel: "Decline",completion: {(UIAlertAction)
                in
                self.spinner?.startAnimating()
                let request = TripBookingRequests.Request(uid: "\(trip.uid)", trip_id: "\(trip.trip_id)", creater_id: UserManager.shared.getUserId()!, status: ("3") , position: position)
                self.interactor?.updateTicket(request: request)
            })
        }
        else  {
            AlertController.showAlert("Trip Deleted", message: "This trip has beed deleted")
        }
    }
}
