//
//  TripCommentWorker.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 4/4/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class TripCommentWorker
{
    func getTripComments(trip_id : String,completion: @escaping ([Comment], Error?) -> Void)
    {
        MainWorker.taskForGETRequest(url: MainWorker.Endpoints.getComments(trip_id).url, responseType: TripComment.Response.self){ (response,error)
            in
            if let response = response {
                completion(response.data,nil)
            }
            else {
                completion([],error)
            }
        }
    }
    
    func sendCommentRequest(body: Comment,completion: @escaping (Comment?, Error?) -> Void)
    {
        var params = [String:String] ()
        params ["uid"] = String(body.uid)
        params ["trip_id"] = String(body.trip_id)
        params ["name"] = String(body.name)
        params ["phone"] = String(body.phone)
        params ["comment"] = body.comment
        params ["cmnt_time"] = String(body.cmnt_time)
        params ["creater_id"] = String(body.creater_id)
         params ["title"] = String(body.title)
        MainWorker.taskForPOSTRequest(url: MainWorker.Endpoints.addComment.url, responseType: TripComment.AddCommentResponse.self, parameters: params){ (response,error)
            in
            if let response = response {
                
                completion( response.data, nil)
            }
            else {
                completion(nil,error)
            }
        }
    }
    
    func deleteCommentRequest(id: String,completion: @escaping (Comment?, Error?) -> Void)
    {
        var params = [String:String] ()
        params ["cmnt_id"] = id
    
        MainWorker.taskForPOSTRequest(url: MainWorker.Endpoints.deleteComment.url, responseType: TripComment.AddCommentResponse.self, parameters: params){ (response,error)
            in
            if let response = response {
                
                completion( response.data, nil)
            }
            else {
                completion(nil,error)
            }
        }
    }
}
