//
//  RecentTripCommentsRouter.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 4/5/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RecentTripCommentsRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol RecentTripCommentsDataPassing
{
  var dataStore: RecentTripCommentsDataStore? { get }
}

class RecentTripCommentsRouter: NSObject, RecentTripCommentsRoutingLogic, RecentTripCommentsDataPassing
{
  weak var viewController: RecentTripCommentsViewController?
  var dataStore: RecentTripCommentsDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: RecentTripCommentsViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: RecentTripCommentsDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
