//
//  RecentTripCommentsModels.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 4/5/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RecentTripComments
{
  // MARK: Use cases
  
 
    struct Response : Codable
    {
        let success: Bool
        let data: [Comment]
    }
    struct ResponseTrip : Codable
    {
        let data: Trip
        let success: Bool
    }
   
  
}
