//
//  RecentTripCommentsWorker.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 4/5/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class RecentTripCommentsWorker
{
    func getTripCommentsByUserId(completion: @escaping ([Comment], Error?) -> Void)
    {
        MainWorker.taskForGETRequest(url: MainWorker.Endpoints.getCommentsByUserId.url, responseType: RecentTripComments.Response.self){ (response,error)
            in
            if let response = response {
                completion(response.data,nil)
            }
            else {
                completion([],error)
            }
        }
    }
    
    func getTripDetails(trip_id: String, completion: @escaping (Trip?, Error?) -> Void)
    {
        var params = [String:String] ()
        params ["uid"] =  UserManager.shared.getUserId() ?? "0"
        params ["trip_id"] = trip_id
        
        MainWorker.taskForPOSTRequest(url: MainWorker.Endpoints.getTrip.url, responseType: RecentTripComments.ResponseTrip.self, parameters: params){ (response,error)
            in
            if let response = response {
                
                completion( response.data, nil)
            }
            else {
                completion(nil,error)
            }
        }
    }
}
