//
//  RecentTripCommentsPresenter.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 4/5/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecentTripCommentsPresentationLogic
{
  func presentList(comments: [Comment], error: Error?)
     func handleTripData(trip: Trip?, error: Error?)
}

class RecentTripCommentsPresenter: RecentTripCommentsPresentationLogic
{
  weak var viewController: RecentTripCommentsDisplayLogic?
  
  // MARK: Do something
    func presentList(comments: [Comment], error: Error?)
    {
        viewController?.showComments(comments: comments, error: error)
    }
    func handleTripData(trip: Trip?, error: Error?){
        viewController?.handleTripData(trip: trip, error: error)
    }
}
