//
//  DetailTripRouter.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/20/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailTripRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol DetailTripDataPassing
{
  var dataStore: DetailTripDataStore? { get set }
}

class DetailTripRouter: NSObject, DetailTripRoutingLogic, DetailTripDataPassing
{
  weak var viewController: DetailTripViewController?
  var dataStore: DetailTripDataStore?
 
}
