//
//  DetailTripWorker.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/20/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailTripWorker
{
    
    func sendTicketrequest(body: DetailTrip.RequestTicket,completion: @escaping (Bool, String) -> Void)
    {
        var params = [String:String] ()
        params ["uid"] = body.uid
        params ["trip_id"] = body.trip_id
        params ["status"] = body.status
        params ["creater_id"] = body.creater_id
        MainWorker.taskForPOSTRequest(url: MainWorker.Endpoints.bookTicket.url, responseType: DetailTrip.ResponseTicketBooking.self, parameters: params){ (response,error)
            in
            if let response = response {
                
                completion( response.success, String(response.uid))
            }
            else {
                completion(false,error?.localizedDescription ?? "")
            }
        }
    }
    
    func deleteTicketrequest(body: DetailTrip.RequestDeleteTicket,completion: @escaping (Bool, String) -> Void)
    {
        var params = [String:String] ()
        params ["uid"] = body.uid
        params ["trip_id"] = body.trip_id
        
        MainWorker.taskForPOSTRequest(url: MainWorker.Endpoints.deleteTicket.url, responseType: DetailTrip.ResponseDeleteTicket.self, parameters: params){ (response,error)
            in
            if let response = response {
                
                completion( response.success, response.data)
            }
            else {
                completion(false,error?.localizedDescription ?? "")
            }
        }
    }
    
    func deleteTrip(body: DetailTrip.RequestDeleteTrip,completion: @escaping (Bool, String) -> Void)
    {
        var params = [String:String] ()
        params ["trip_id"] = body.trip_id
        MainWorker.taskForPOSTRequest(url: MainWorker.Endpoints.deleteTrip.url, responseType: DetailTrip.ResponseTicketBooking.self, parameters: params){ (response,error)
            in
            if let response = response {
                
                completion( response.success, String(response.uid))
            }
            else {
                completion(false,error?.localizedDescription ?? "")
            }
        }
    }
}
