//
//  DetailTripPresenter.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/20/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailTripPresentationLogic
{
    func updateBookingstatus(success: Bool, message: String)
    func deleteBookingRequest(success: Bool, message: String)
    func deleteTrip(success: Bool, message: String)
}

class DetailTripPresenter: DetailTripPresentationLogic
{
  weak var viewController: DetailTripDisplayLogic?
  
  // MARK: Do something
   func deleteTrip(success: Bool, message: String) {
        viewController?.deleteTrip(success: success, message: message)
    }
    
    func updateBookingstatus(success: Bool, message: String) {
        viewController?.updateBookingStatus(success: success, message: message)
    }
    func deleteBookingRequest(success: Bool, message: String)
    {
        viewController?.deleteBookingRequest(success: success, message: message )
    }
}
