//
//  DestinationListInteractor.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/9/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DestinationListBusinessLogic
{
    func getTrips()
    func updateTicket(request: DestinationList.RequestTicket)
    func deleteTicketRequest(request: DestinationList.RequestDeleteTicket)
    func deleteTrip(request: DestinationList.RequestDeleteTrip)
}

protocol DestinationListDataStore
{
}

class DestinationListInteractor: DestinationListBusinessLogic, DestinationListDataStore
{
    var presenter: DestinationListPresentationLogic?
    var worker: DestinationListWorker?
    
    func updateTicket(request: DestinationList.RequestTicket) {
        worker = DestinationListWorker()
        worker?.sendTicketrequest(body : request,completion: {(success,message)
            in
            self.presenter?.updateBookingstatus(success: success, message: message,posintion: request.position)
        }
        )
    }
    
    func deleteTicketRequest(request: DestinationList.RequestDeleteTicket) {
        worker = DestinationListWorker()
        worker?.deleteTicketrequest(body : request,completion: {(success,message)
            in
            self.presenter?.deleteBookingRequest(success: success, message: message,posintion: request.position)
        }
        )
    }
    
    func deleteTrip(request: DestinationList.RequestDeleteTrip) {
        worker = DestinationListWorker()
        worker?.deleteTrip(body : request,completion: {(success,message)
            in
            self.presenter?.deleteTrip(success: success, message: message,posintion: request.position)
        }
        )
    }
    
    func getTrips()
    {
        worker = DestinationListWorker()
        worker?.getTrips(completion: {(trips,error)
            in
            self.presenter?.presentList(trip: trips, error: error)
        }
        )
    }
}
