//
//  DestinationListViewController.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/9/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit
import CoreLocation
import CoreData
protocol DestinationListDisplayLogic: class
{
    func displaySomething(trip: [Trip], error: Error?)
    func updateBookingStatus(success: Bool, message: String,posintion: Int)
    func deleteBookingRequest(success: Bool, message: String, posintion: Int)
    func deleteTrip(success: Bool, message: String, posintion: Int)
}

class DestinationListViewController: UIViewController, DestinationListDisplayLogic
{
    //MARK: outlets
    @IBOutlet weak var noItemView: UIView!
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var navigationIten: UINavigationItem!
    @IBOutlet weak var navigationBar: UINavigationBar!
    
    // MARK: Variables
    var dataController : DataController!
    var fetchedResultController : NSFetchedResultsController<NSTripObject>!
    var spinner: UIActivityIndicatorView?
    var selectedTrip:NSTripObject?
    var interactor: DestinationListBusinessLogic?
    var router: (NSObjectProtocol & DestinationListRoutingLogic & DestinationListDataPassing)?
    var locManager = CLLocationManager()
    var appDelegate: AppDelegate!
    
    // MARK: Lifecycle methods
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.navigationIten.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(showfindRouteController))
        self.navigationIten.rightBarButtonItem?.tintColor = UIColor.white
        self.navigationIten.leftBarButtonItem = UIBarButtonItem(title: "Logout", style: .plain, target: self, action: #selector(logOut))
        self.navigationIten.rightBarButtonItem?.tintColor = UIColor.white
        self.navigationIten.leftBarButtonItem?.tintColor = UIColor.white
        setStatusBarStyle()
        spinner = SpinnerView.showLoader(view: view)
        appDelegate = UIApplication.shared.delegate as! AppDelegate
        let tapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(imageTapped(tapGestureRecognizer:)))
        noItemView.isUserInteractionEnabled = true
        noItemView.addGestureRecognizer(tapGestureRecognizer)
        setupLocationManager()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        noItemView.isHidden = true
        setUpFetchResultController()
        getTrips()
    }
    
    // MARK: Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
        if(segue.identifier == "detailSegue"){
            let destinationVC = segue.destination as! UITabBarController
            let vc = destinationVC.viewControllers![0] as! DetailTripViewController
            let tripRequestsViewController = destinationVC.viewControllers![1] as! TripRequestsViewController
            let tripCommentViewController = destinationVC.viewControllers![2] as! TripCommentViewController
            vc.trip = selectedTrip
            vc.dataController = dataController
            tripCommentViewController.trip = selectedTrip
            tripCommentViewController.dataController = dataController
            tripRequestsViewController.tripSelected = selectedTrip
            tripRequestsViewController.dataController = dataController
        }
    }
    
    
    // MARK: Setup
    private func setup()
    {
        let viewController = self
        let interactor = DestinationListInteractor()
        let presenter = DestinationListPresenter()
        let router = DestinationListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    // Settingup CoreData result for image collection
    //Entity: Images
    fileprivate func setUpFetchResultController() {
        let predicate = NSPredicate(format: "trip_type = 0")
        let fetchRequest: NSFetchRequest<NSTripObject> = NSTripObject.fetchRequest()
        let sortDescriptor = NSSortDescriptor(key: "id", ascending: false)
        fetchRequest.predicate = predicate
        fetchRequest.sortDescriptors = [sortDescriptor]
        fetchedResultController = NSFetchedResultsController(fetchRequest: fetchRequest, managedObjectContext: dataController.viewContext, sectionNameKeyPath: nil, cacheName: nil)
        fetchedResultController.delegate = self
        do{
            try  fetchedResultController.performFetch()
        }  catch {
            
        }
    }
    //MARK: Private methods
    func setupLocationManager() {
        locManager.desiredAccuracy = kCLLocationAccuracyBest
        locManager.delegate = self
    }
    
    func getTrips(){
        locManager.requestWhenInUseAuthorization()
        if (CLLocationManager.authorizationStatus() == CLAuthorizationStatus.authorizedWhenInUse ||
            CLLocationManager.authorizationStatus() == CLAuthorizationStatus.authorizedAlways){
            guard let currentLocation = locManager.location else {
                spinner?.startAnimating()
                interactor?.getTrips()
                return
            }
            UserManager.shared.setUserLocation(lat: currentLocation.coordinate.latitude, lng: currentLocation.coordinate.longitude)
            spinner?.startAnimating()
            interactor?.getTrips()
        }
    }
    
    func loadRoutes(){
        for tripObject in fetchedResultController.sections![0].objects!  {
            let trip = tripObject as! NSTripObject
            if  let _ = TripModel.mapRoute[trip.id!]
            {
                self.tableView.reloadData()
                continue
            }
            let request = MKDirectionsRequest()
            let coordinate = CLLocationCoordinate2D(latitude: trip.latstart,longitude : trip.longstart)
            let coordinateEnd = CLLocationCoordinate2D(latitude: trip.latend,longitude : trip.longend)
            let mkPlacemark = MKPlacemark(coordinate: coordinate)
            let mkPlacemark2 = MKPlacemark(coordinate: coordinateEnd)
            request.source = MKMapItem(placemark: mkPlacemark)
            request.destination = MKMapItem(placemark: mkPlacemark2)
            request.requestsAlternateRoutes = false
            let directions = MKDirections(request: request)
            directions.calculate(completionHandler: {(response, error) in
                
                if error != nil {
                    print("saved mappp \(error.debugDescription)")
                } else {
                    print("saved mapppv")
                    TripModel.mapRoute[trip.id!] = response
                    self.tableView.reloadData()
                }
            })
        }
    }
    
    
    //MARK: IBAction
    @objc func imageTapped(tapGestureRecognizer: UITapGestureRecognizer)
    {
        noItemView.isHidden = true
        spinner?.startAnimating()
        interactor?.getTrips()
    }
    
    @objc func showfindRouteController(_ updateLocation: Bool){
        self.performSegue(withIdentifier: "findRouteSegue", sender: nil)
    }
    @objc func logOut(){
        AlertController.showAlert("Logout", message: "Sure to logout?",actionLabel: "Logout",completion: {
            (alert)
            in
            UserManager.shared.resetUserData()
            self.dismiss(animated: true, completion: nil)
        })
    }
    
    // MARK: Delegate method -> DestinationListDisplayLogic
    func updateBookingStatus(success: Bool, message: String,posintion: Int) {
        spinner?.stopAnimating()
        if success {
            (fetchedResultController.sections?[0].objects![posintion] as! NSTripObject ).status = Int32(message)!
            try! dataController.viewContext.save()
        }
        else {
            AlertController.showAlert("Error", message: message)
        }
    }
    
    func deleteTrip(success: Bool, message: String, posintion: Int){
        spinner?.stopAnimating()
        if success {
            dataController.viewContext.delete( (fetchedResultController.sections?[0].objects![posintion] as! NSTripObject ))
            try! dataController.viewContext.save()
        }
        else{
            AlertController.showAlert("Can not delete Trip", message: message)
        }
        if  fetchedResultController.sections?[0].numberOfObjects == 0
        {     noItemView.isHidden = false
        }
    }
    
    func deleteBookingRequest(success: Bool, message: String, posintion: Int){
        spinner?.stopAnimating()
        if success {
            (fetchedResultController.sections?[0].objects![posintion] as! NSTripObject ).status = -1
            try! dataController.viewContext.save()
        }else {
            AlertController.showAlert("Error", message: message)
        }
    }
    
    func displaySomething(trip: [Trip], error: Error?) {
        if error == nil {
            saveToCoreData(trips: trip)
        }
        if trip.count == 0
        {
            spinner?.stopAnimating()
            if fetchedResultController.sections?[0].numberOfObjects == 0 {
                noItemView.isHidden = false
            }
        }
    }
    
    
    func saveToCoreData(trips : [Trip]){
        let backgroundContext : NSManagedObjectContext! = dataController.backgroundContext
        //deleting old items
        for trip in self.fetchedResultController.sections![0].objects!
        {
            let id = (trip as AnyObject).objectID
            backgroundContext.perform {
                let backgroundObject = backgroundContext.object(with: id!) as! NSTripObject
                backgroundContext.delete(backgroundObject)
                try? backgroundContext.save()
            }
        }
        backgroundContext.perform { for trip in  trips {
            let img = NSTripObject(context: self.dataController.backgroundContext)
            img.id = trip.id
            img.count_accept = trip.count_accept
            img.count  = trip.count
            img.enddate = trip.enddate
            img.startsdate = trip.startsdate
            img.is_deleted = trip.deleted
            img.latend = trip.latend
            img.latstart = trip.latstart
            img.longend = trip.longend
            img.longstart = trip.longstart
            img.name = trip.name
            img.pals = Int32(trip.pals)
            img.phone = trip.phone
            if let status = trip.status {
                img.status =  Int32(status)
            }
            img.title = trip.title
            img.trip_description = trip.description
            img.uid = Int32(trip.uid)
            img.trip_type = Int32(MainWorker.TripType.allTrip.rawValue)
            do {
                try backgroundContext.save()
            }
            catch {
            }
            }
            DispatchQueue.main.async {
                self.spinner?.stopAnimating()
                self.loadRoutes()
            }
        }
    }
}

//MARK: TableView Delegates
extension DestinationListViewController : UITableViewDataSource, UITableViewDelegate{
    func showRoute(_ response: MKDirectionsResponse, _ mapView: MKMapView) {
        for route in response.routes {
            mapView.add(route.polyline,
                        level: MKOverlayLevel.aboveRoads)
        }
    }
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return fetchedResultController.sections?.count ?? 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return  fetchedResultController.sections?[section].numberOfObjects ?? 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "TripTableViewCell") as! TripTableViewCell
        let trip = fetchedResultController.object(at: indexPath)
        cell.dateLable?.text = "\(appDelegate.formatter.string(from: Date(milliseconds: Int(trip.startsdate)))) to \(appDelegate.formatterLong.string(from: Date(milliseconds: Int(trip.enddate))))"
        cell.titleLabel?.text = trip.title
        cell.userName?.text = trip.name
        let availableSeats = Int(trip.pals)  - Int(trip.count_accept ?? "0")!
        cell.seatLabel?.text = "\(availableSeats == 0 ? "No" : String(availableSeats) ) seats available"
        cell.descriptionLabel?.text = (trip.trip_description)
        cell.initialLabel?.text = trip.name?.components(separatedBy: " ").reduce("") { ($0 == "" ? "" : "\($0.first!)") + "\($1.first!)" }.uppercased()
        cell.ticketButton.addTarget(self, action: #selector(self.ticketButtonTapped(sender:)), for: .touchUpInside)
        let tapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(showOwnerInfo(tapGestureRecognizer:)))
        cell.userInfoStackView.isUserInteractionEnabled = true
        cell.userInfoStackView.addGestureRecognizer(tapGestureRecognizer)
        if Int(trip.uid) == Int(UserManager.shared.getUserId()!) {
            cell.ticketButton.setImage(UIImage(named: "deleted.png"), for: .normal)
        }
        else if -1 ==  trip.status {
            cell.ticketButton.setImage(UIImage(named: "book_seat.png"), for: .normal)
        }
        else if trip.status == 0 {
            cell.ticketButton.setImage(UIImage(named: "waiting.png"), for: .normal)
        }
        else if trip.status == 1 {
            cell.ticketButton.setImage(UIImage(named: "accepted.png"), for: .normal)
        }
        else if trip.status == 3 {
            cell.ticketButton.setImage(UIImage(named: "cancelled.png"), for: .normal)
        }
        
        if nil ==  trip.count {
            cell.countTextLabel.text = "No one request for booking yet"
        }
        else {
            cell.countTextLabel.text = "\(trip.count ?? "No") \(trip.count! == "1" ? "person" : "people") request for booking"
        }
        
        if  let _ = trip.id ,let directionsResponse = TripModel.mapRoute[trip.id!]
        {
            showRoute(directionsResponse, cell.mapView)
            cell.mapView?.setRegion( MKCoordinateRegion(center: CLLocationCoordinate2D(latitude: trip.latstart, longitude: trip.longstart), span: MKCoordinateSpan(latitudeDelta: 4, longitudeDelta: 4)), animated: true)
        }
        return cell
    }
    
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        selectedTrip = fetchedResultController.object(at: indexPath)
        self.performSegue(withIdentifier: "detailSegue", sender: nil)
    }
    
    @objc func showOwnerInfo(tapGestureRecognizer : UITapGestureRecognizer){
        guard let cell = tapGestureRecognizer.view?.superview?.superview?.superview?.superview?.superview as? TripTableViewCell else {
            return
        }
        
        if let indexPath = tableView.indexPath(for: cell) {
            let trip: NSTripObject = fetchedResultController.object(at: indexPath)
            AlertController.showAlert(trip.title!, message: "Owner -: \(trip.name!)\nContact-: \(trip.phone!)")
        }
    }
    
    @objc func ticketButtonTapped(sender : UIButton){
        guard let cell = sender.superview?.superview?.superview?.superview?.superview as? TripTableViewCell else {
            return 
        }
        
        if let indexPath = tableView.indexPath(for: cell) {
            let trip: NSTripObject = fetchedResultController.object(at: indexPath)
            if Int(trip.uid) == Int(UserManager.shared.getUserId()!) {
                AlertController.showAlert("Delete Trip?", message: "Really want to delete this trip?",actionLabel: "Delete",completion: {(UIAlertAction)
                    in
                    self.spinner?.startAnimating()
                    let request = DestinationList.RequestDeleteTrip(trip_id: trip.id!, position: indexPath.row)
                    self.interactor?.deleteTrip(request: request)
                })
            }
            else   if -1 == trip.status {
                AlertController.showAlert("Book seat?", message: "Please send booking request for this trip? \nYou will be on waiting untill owner accept your request even seats are full",actionLabel: "Book",completion: {(UIAlertAction)
                    in
                    self.spinner?.startAnimating()
                    let request = DestinationList.RequestTicket(uid: UserManager.shared.getUserId()!, trip_id: trip.id!, creater_id: "\(trip.uid)", status: "\(0)" , position: indexPath.row)
                    self.interactor?.updateTicket(request: request)
                })
            }
            else {
                let messsage = trip.status == 0 ? "Your booking request is pending \n Want to delete it?" : (trip.status == 1 ? "Your booking request is accepted \n Want to delete it?" : "Your booking request has declined \n Want to delete it?")
                AlertController.showAlert("Delete booking request?", message: messsage,actionLabel: "Delete",completion: {(UIAlertAction)
                    in
                    self.spinner?.startAnimating()
                    let request = DestinationList.RequestDeleteTicket(uid: UserManager.shared.getUserId()!, trip_id: trip.id! , position: indexPath.row)
                    self.interactor?.deleteTicketRequest(request: request) })
            }
            
        }
    }
}

//MARK: LocationManagerDelegate Delegate
extension DestinationListViewController: CLLocationManagerDelegate {
    func locationManager(_ manager: CLLocationManager, didChangeAuthorization status: CLAuthorizationStatus) {
        locationHandler()
    }
    
    func locationHandler() {
        if CLLocationManager.locationServicesEnabled() == true {
            if (CLLocationManager.authorizationStatus() == .authorizedWhenInUse){
                getTrips()
            }
        }
    }
}

//MARK: NSFetchedResultsControllerDelegate
extension DestinationListViewController:NSFetchedResultsControllerDelegate {
    func controller(_ controller: NSFetchedResultsController<NSFetchRequestResult>, didChange anObject: Any, at indexPath: IndexPath?, for type: NSFetchedResultsChangeType, newIndexPath: IndexPath?) {
        switch type {
        case .insert:
            tableView.insertRows(at: [newIndexPath!], with: .fade)
            break
        case .delete:
            tableView.deleteRows(at: [indexPath!], with: .fade)
            break
        case .update:
            tableView.reloadRows(at: [indexPath!], with: .fade)
        case .move:
            tableView.moveRow(at: indexPath!, to: newIndexPath!)
        }
    }
    
    
    
    
    func controllerWillChangeContent(_ controller: NSFetchedResultsController<NSFetchRequestResult>) {
        tableView.beginUpdates()
    }
    
    func controllerDidChangeContent(_ controller: NSFetchedResultsController<NSFetchRequestResult>) {
        tableView.endUpdates()
    }
    
}

