//
//  DestinationListPresenter.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/9/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DestinationListPresentationLogic
{
    func presentList(trip: [Trip], error: Error?)
    func updateBookingstatus(success: Bool, message: String,posintion: Int)
    func deleteBookingRequest(success: Bool, message: String,posintion: Int)
    func deleteTrip(success: Bool, message: String,posintion: Int)
}

class DestinationListPresenter: DestinationListPresentationLogic
{
    weak var viewController: DestinationListDisplayLogic?
    
    func deleteTrip(success: Bool, message: String, posintion: Int) {
        viewController?.deleteTrip(success: success, message: message, posintion: posintion)
    }
    
    func updateBookingstatus(success: Bool, message: String,posintion: Int) {
        viewController?.updateBookingStatus(success: success, message: message, posintion: posintion)
    }
    
     func presentList(trip: [Trip], error: Error?)
    {
         viewController?.displaySomething(trip: trip, error: error)
    }
    func deleteBookingRequest(success: Bool, message: String,posintion: Int)
    {
        viewController?.deleteBookingRequest(success: success, message: message, posintion: posintion)
    }
}
