//
//  DestinationListModels.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/9/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DestinationList
{
    // MARK: Use cases
   struct RequestTicket: Codable
    {
        let uid: String
        let trip_id: String
        let creater_id: String
        let status: String
        let position: Int
    }
    struct RequestDeleteTicket: Codable
    {
        let uid: String
        let trip_id: String
        let position: Int
    }
    struct RequestDeleteTrip: Codable
    {
        
        let trip_id: String
        let position: Int
    }
    struct ResponseDeleteTicket: Codable
    {
        let success: Bool
        let data: String
        
    }
    struct Response : Codable
    {
        let success: Bool
        let data: [Trip]
    }
    struct ResponseTicketBooking: Codable
    {
        let success: Bool
        let uid: Int
    }
    
    
}
