//
//  DestinationListRouter.swift
//  OneDirection
//
//  Created by Ashish Nautiyal on 3/9/19.
//  Copyright (c) 2019 Ashish  Nautiyal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DestinationListRoutingLogic
{
    func routeToDetailTrip(segue: UIStoryboardSegue?)
}

protocol DestinationListDataPassing
{
    var dataStore: DestinationListDataStore? { get set}
}

class DestinationListRouter: NSObject, DestinationListRoutingLogic, DestinationListDataPassing
{
    weak var viewController: DestinationListViewController?
    var dataStore: DestinationListDataStore?
    
    // MARK: Routing
    func routeToDetailTrip(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
        } else {
       }
    }
    
    // MARK: Navigation
    
    func navigateToSomewhere(source: DestinationListViewController, destination: DetailTripViewController)
    {
        source.present(destination, animated:true, completion: nil)
    }
    
 
}
